name: pp

options:
  bundleIdPrefix: io.github.takeiteasy
  createIntermediateGroups: true
  deploymentTarget:
    macOS: "12.0"

settings:
  GCC_C_LANGUAGE_STANDARD: c11

targets:
  pp:
    type: application
    platform: macOS
    info:
      path: Info.plist
    sources:
        - tests/
        - pp.c
    dependencies:
        - sdk: Cocoa.framework
    settings:
        HEADER_SEARCH_PATHS: [$(PROJECT_DIR)/src, $(PROJECT_DIR)/ext, $(PROJECT_DIR)/, $(PROJECT_DIR)/lib/bitmap]
